trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build the app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'weapp-ecommerce'
    appType: 'webApp'
    appName: 'ecommerce365'
    package: '$(System.DefaultWorkingDirectory)/build'
